spring:
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.47.61.175:3306/business_intelligence?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: Developer
    password: 69e78a08-6df8-11e7-a350-00163e013527
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          # 自动创建表
          auto: update
    
